exclude: "^{{cookiecutter\\.project_name}}/"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
